### ISSUE TITLE
Anyone hiring gophers?

### ISSUE THREAD

**Issue by faddat** [buffalodevs/BuffaloTechnologyCompanies#15]
I write go and specialize in some combination of p2p, decentralized systems, and containers.  

I currently live in Asia but am from Buffalo originally.

**Comment by amweiss** [comment]
A couple companies use it from internal work/research, don't know of anyone specifically hiring for it.

**Comment by colin-higgins** [comment]
If you find out about anyone hiring for it in Buffalo though, please feel free to re-open.
