### ISSUE TITLE
IT Staffing Agency to add

### ISSUE THREAD

**Issue by APProfessionals** [buffalodevs/BuffaloTechnologyCompanies#24]
Would you be able to add AP Professionals to the agency list?

**Comment by colin-higgins** [comment]
Sure, what URL should I use?

**Comment by APProfessionals** [comment]
http://approfessionals.com/buffalo/

Thank you so much!

Amy Bessel | Placement Director
IT Division
AP. Professionals
5110 Main Street, Walker Center, Suite 100 |Williamsville, NY 14221
Phone: 716.635.0290 | Fax: 716.635.0075
[cid:image004.jpg@01D33EB0.0577A650]amy@apbuffalo.com<mailto:amy@apbuffalo.com>   |   www.approfessionals.com/buffalo<http://www.approfessionals.com/buffalo>
